#!/bin/sh

_title=""
_script=""
_arguments=""
expect_status=0
check_output=0
expect_output=""

title()
{
  _title=$1
}

script()
{
  _script=$1
}

arguments()
{
  _arguments=$1
}

expect_status_success()
{
  expect_status=0
}

expect_status_failure()
{
  expect_status=1
}

expect()
{
  expect_status=$1
  check_output=1
  expect_output=$2
}

expect_success()
{
  expect_status=0
  check_output=1
  expect_output=$1
}

expect_failure()
{
  expect_status=1
  check_output=1
  expect_output=$1
}

run()
{
  if [ $expect_status -eq 0 ]; then
    output=$(echo "$_script" | bin/hook $_arguments)
  else
    output=$(echo "$_script" | bin/hook $_arguments 2>&1)
  fi
  status=$?
  n=0
  if [ $status -ne $expect_status ]; then
    n=$(($n + 1))
  fi
  if [ $check_output -eq 1 ] && [ "$output" != "$expect_output" ]; then
    n=$(($n + 1))
  fi
  result=$([ $n -eq 0 ] && echo "Passed" || echo "Failed")
  echo "[$result] $_title"
  exit $n
}
