#!/bin/sh

. test/_test

title "Append array element"

script "var arr1 = [];
arr1[] = 'foo';
println(arr1);

var arr2 = [[]];
arr2[0][] = 'foo';
println(arr2);

var arr3 = [[[]]];
arr3[0][0][] = 'foo';
println(arr3);

var arr4 = [[1, 2, 3]];
arr4[0][] = 4;
println(arr4);"

expect_success "['foo']
[['foo']]
[[['foo']]]
[[1, 2, 3, 4]]"

run
