#!/bin/sh

. test/_test

title "Array difference"

script "println([] - ['foo']);
println(['foo'] - []);
println(['foo', 'bar', 'baz'] - ['bar']);
let arr = ['foo', 'bar', 'baz', 'bar', 'qux'];
println(arr - ['bar', 'baz']);"

expect_success "[]
['foo']
['foo', 'baz']
['foo', 'qux']"

run
