#!/bin/sh

. test/test

title "Array concatenation"

script "println([] + ['foo']);
println(['foo'] + []);
println(['foo', 'bar'] + ['baz']);
let arr = ['foo', 'bar'];
println(arr + ['baz', 'qux']);"

expect_success "['foo']
['foo']
['foo', 'bar', 'baz']
['foo', 'bar', 'baz', 'qux']"

run
