#!/bin/sh

. test/__test

title "Array: add element"

script "let arr1 = [];
arr1[] = 'foo';
println(arr1);

let arr2 = [[]];
arr2[0][] = 'foo';
println(arr2);

let arr3 = [[[]]];
arr3[0][0][] = 'foo';
println(arr3);

let arr4 = [[1, 2, 3]];
arr4[0][] = 4;
println(arr4);"

expect_success "['foo']
[['foo']]
[[['foo']]]
[[1, 2, 3, 4]]"

run
