#!/bin/sh

. test/__test

title "Array: equal"

script "println([] == []);
println([1] == [1]);
println([1] == [1, 2]);
println([1, 2] == [1]);
println([1, 2] == [1, 2]);
println([1, 2] == [2, 1]);
const a = ['foo'];
println(a == a);"

expect_success "true
true
false
false
true
false
true"

run
