#!/bin/sh

. test/test

title "Array equal"

script "println([] == []);
println([1] == [1]);
println([1] == [1, 2]);
println([1, 2] == [1]);
println([1, 2] == [1, 2]);
println([1, 2] == [2, 1]);"

expect_success "true
true
false
false
true
false"

run
