#!/bin/sh

. test/__test

title "Array: append element"

script "let mut arr1 = [];
arr1[] = 'foo';
println(arr1);

let mut arr2 = [[]];
arr2[0][] = 'foo';
println(arr2);

let mut arr3 = [[[]]];
arr3[0][0][] = 'foo';
println(arr3);

let mut arr4 = [[1, 2, 3]];
arr4[0][] = 4;
println(arr4);"

expect_success "['foo']
[['foo']]
[[['foo']]]
[[1, 2, 3, 4]]"

run
