#!/bin/sh

. test/__test

title "Assignment"

script "let mut a;
a = 1;
a += 1;
a -= 1;
a *= 1;
a /= 1;
a %= 1;
a++;
a--;

let mut b = [];
b[] = 1;
b[0] += 1;
b[0] -= 1;
b[0] *= 1;
b[0] /= 1;
b[0] %= 1;
b[0]++;
b[0]--;

let mut c = [[]];
c[0][] = 1;
c[0][0] += 1;
c[0][0] -= 1;
c[0][0] *= 1;
c[0][0] /= 1;
c[0][0] %= 1;
c[0][0]++;
c[0][0]--;"

expect_success ""

run
