#!/bin/sh

. test/_test

title "Assignment"

script "var a;
a = 1;
a += 1;
a -= 1;
a *= 1;
a /= 1;
a %= 1;
a++;
a--;

var b = [];
b[] = 1;
b[0] += 1;
b[0] -= 1;
b[0] *= 1;
b[0] /= 1;
b[0] %= 1;
b[0]++;
b[0]--;

var c = [[]];
c[0][] = 1;
c[0][0] += 1;
c[0][0] -= 1;
c[0][0] *= 1;
c[0][0] /= 1;
c[0][0] %= 1;
c[0][0]++;
c[0][0]--;"

expect_success ""

run
