#!/bin/sh

. test/test

title "Built-in function is_empty()"

script "println(is_empty('foo'));
println(is_empty(''));
println(is_empty([1, 2, 3]));
println(is_empty([]));"

expect_success "false
true
false
true"

run
