#!/bin/sh

. test/__test

title "Built-in function slice()"

script "let str = 'abc';
println(slice(str, 0, 4));
println(slice(str, 1, 3));
println(slice(str, 2, 3));

let arr = ['a', 'b', 'c'];
println(slice(arr, 0, 4));
println(slice(arr, 1, 3));
println(slice(arr, 2, 3));"

expect_success "abc
bc
c
['a', 'b', 'c']
['b', 'c']
['c']"

run
