#!/bin/sh

. test/__test

title "Built-in function join()"

script "println(join(['a', 'b', 'c'], ','));
println(join(['a', 'b'], ','));
println(join(['a'], ','));
println(join([], ','));"

expect_success "a,b,c
a,b
a"

run
