#!/bin/sh

. test/__test

title "Delete array element"

script "let mut arr = [1, 2, 3, ['foo', 'bar', 'baz']];
delete arr[1];
println(arr);

delete arr[2][1];
println(arr);"

expect_success "[1, 3, ['foo', 'bar', 'baz']]
[1, 3, ['foo', 'baz']]"

run
