#!/bin/sh

. test/_test

title "Error from compare(): cannot compare X and Y"

script "let a = compare(1, 'foo');"

expect_failure "runtime error: cannot compare 'number' and 'string'
  at compare() in <native>
  at main() in <stdin>:1"

run
