#!/bin/sh

. test/test

title "Error from abs(): expected number but got X"

script "let a = abs('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at abs() in <native>
  at <main>() in <stdin>:1"

run
