#!/bin/sh

. test/_test

title "Error from floor(): expected number but got X"

script "let a = floor('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at floor() in <native>
  at <main>() in <stdin>:1"

run
