#!/bin/sh

. test/__test

title "Error from strings.hash(): expected string but got X"

script "const hash = require('strings').hash;
const a = hash(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at hash() in <native>
  at main() in <stdin>:2"

run
