#!/bin/sh

. test/__test

title "Error from math.pow(): expected number but got X (2)"

script "let math = require('math');
let a = math.pow(1, 'foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at pow() in <native>
  at main() in <stdin>:2"

run
