#!/bin/sh

. test/test

title "Error from float(): cannot convert empty string to number"

script "let a = float('');"

expect_failure "runtime error: invalid type: cannot convert empty string to 'number'
  at float() in <native>
  at <main>() in <stdin>:1"

run
