#!/bin/sh

. test/__test

title "Error from assert(): expected string but got X"

script "assert(true, 1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at assert() in <native>
  at main() in <stdin>:1"

run
