#!/bin/sh

. test/__test

title "Error from str(): cannot convert X to string"

script "let a = str([]);"

expect_failure "runtime error: invalid type: cannot convert 'array' to 'string'
  at str() in <native>
  at main() in <stdin>:1"

run
