#!/bin/sh

. test/__test

title "Error from int(): cannot convert empty string to number"

script "const a = int('4.9e-324');"

expect_failure "runtime error: invalid type: number literal is too large
  at int() in <native>
  at main() in <stdin>:1"

run
