#!/bin/sh

. test/_test

title "Error invalid type: X has no capacity"

script "println(cap(1));"

expect_failure "runtime error: invalid type: 'number' has no capacity
  at cap() in <native>
  at main() in <stdin>:1"

run
