#!/bin/sh

. test/__test

title "Error from os.system(): expected string but got X"

script "use { system } in os;
system(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at system() in <native>
  at main() in <stdin>:2"

run
