#!/bin/sh

. test/__test

title "Error from sqrt(): expected number but got X"

script "let a = sqrt('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at sqrt() in <native>
  at main() in <stdin>:1"

run
