#!/bin/sh

. test/__test

title "Error from math.ceil(): expected number but got X"

script "use math;
const a = math.ceil('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at ceil() in <native>
  at main() in <stdin>:2"

run
