#!/bin/sh

. test/__test

title "Error from float(): number literal is too large"

script "let a = float('4.9e-324');"

expect_failure "runtime error: invalid type: number literal is too large
  at float() in <native>
  at main() in <stdin>:1"

run
