#!/bin/sh

. test/__test

title "Error from math.pow(): expected number but got X (1)"

script "const math = require('math');
const a = math.pow('foo', 1);"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at pow() in <native>
  at main() in <stdin>:2"

run
