#!/bin/sh

. test/__test

title "Error from math.floor(): expected number but got X"

script "use math;
const a = math.floor('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at floor() in <native>
  at main() in <stdin>:2"

run
