#!/bin/sh

. test/test

title "Error from panic(): expected string but got X"

script "panic(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at panic() in <native>
  at <main>() in <stdin>:1"

run
