#!/bin/sh

. test/__test

title "Error from strings.upper(): expected string but got X"

script "const upper = require('strings').upper;
const a = upper(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at upper() in <native>
  at main() in <stdin>:2"

run
