#!/bin/sh

. test/_test

title "Error from hash(): expected string but got X"

script "let a = hash(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at hash() in <native>
  at main() in <stdin>:1"

run
