#!/bin/sh

. test/__test

title "Error from array(): invalid type"

script "const arr = array('foo');"

expect_failure "runtime error: invalid type: expected integer but got 'string'
  at array() in <native>
  at main() in <stdin>:1"

run
