#!/bin/sh

. test/test

title "Error from float(): cannot convert X to number"

script "let a = float(null);"

expect_failure "runtime error: invalid type: cannot convert 'null' to 'number'
  at float() in <native>
  at <main>() in <stdin>:1"

run
