#!/bin/sh

. test/_test

title "Error from int(): cannot convert empty string to number"

script "let a = int('');"

expect_failure "runtime error: invalid type: cannot convert empty string to 'number'
  at int() in <native>
  at <main>() in <stdin>:1"

run
