#!/bin/sh

. test/__test

title "Error from strings.trim(): expected string but got X"

script "const trim = require('strings').trim;
const a = trim(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at trim() in <native>
  at main() in <stdin>:2"

run
