#!/bin/sh

. test/__test

title "Error from strings.lower(): expected string but got X"

script "const lower = require('strings').lower;
const a = lower(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at lower() in <native>
  at main() in <stdin>:2"

run
