#!/bin/sh

. test/_test

title "Error from len(): X has no length"

script "println(len(1));"

expect_failure "runtime error: invalid type: 'number' has no length property
  at len() in <native>
  at main() in <stdin>:1"

run
