#!/bin/sh

. test/__test

title "Error from math.abs(): expected number but got X"

script "let math = require('math');
let a = math.abs('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at abs() in <native>
  at main() in <stdin>:2"

run
