#!/bin/sh

. test/__test

title "Error from os.getenv(): expected string but got X"

script "use os;
println(os.getenv(1));"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at getenv() in <native>
  at main() in <stdin>:2"

run
