#!/bin/sh

. test/__test

title "Error from ceil(): expected number but got X"

script "let a = ceil('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at ceil() in <native>
  at main() in <stdin>:1"

run
