#!/bin/sh

. test/_test

title "Error from int(): cannot convert X to integer"

script "let a = int(null);"

expect_failure "runtime error: invalid type: cannot convert 'null' to 'integer'
  at int() in <native>
  at main() in <stdin>:1"

run
