#!/bin/sh

. test/_test

title "Error from int(): cannot convert empty string to number"

script "let a = int('4.9e-324');"

expect_failure "runtime error: invalid type: number literal is too large
  at int() in <native>
  at <main>() in <stdin>:1"

run
