#!/bin/sh

. test/__test

title "Error from math.sqrt(): expected number but got X"

script "let math = require('math');
let a = math.sqrt('foo');"

expect_failure "runtime error: invalid type: expected number but got 'string'
  at sqrt() in <native>
  at main() in <stdin>:2"

run
