#!/bin/sh

. test/_test

title "Error from system(): expected string but got X"

script "system(1);"

expect_failure "runtime error: invalid type: expected string but got 'number'
  at system() in <native>
  at main() in <stdin>:1"

run
