#!/bin/sh

. test/_test

title "Error from is_empty(): X has no length"

script "println(is_empty(1));"

expect_failure "runtime error: invalid type: 'number' has no length
  at is_empty() in <native>
  at <main>() in <stdin>:1"

run
