#!/bin/sh

. test/__test

title "Error from float(): cannot convert string to number"

script "const a = float('123 x');"

expect_failure "runtime error: invalid type: cannot convert 'string' to 'number'
  at float() in <native>
  at main() in <stdin>:1"

run
