#!/bin/sh

. test/__test

title "Function declaration"

script "fn f(a, b) {
  return a + b;
}

let g = fn (a, b) {
  return a - b;
};

fn h() {
  fn f() {}
  fn g() {}
  fn h() {}
  fn i() {}
  fn j() {}
  fn k() {}
  fn l() {}
  fn m() {}
  fn n() {}
}

println(f(1, 2));
println(g(3, 2));"

expect_success "3
1"

run
