#!/bin/sh

. test/__test

title "Library strings: upper()"

script "use strings;
println(strings.upper(''));
println(strings.upper('foo'));
println(strings.upper('Bar'));
println(strings.upper('BAZ'));"

expect_success "
FOO
BAR
BAZ"

run
