#!/bin/sh

. test/__test

title "Option: --disasm"

script "fn factorial(n) {
  if (n == 0)
    return 1;
  return n * factorial(n - 1);
}

println(factorial(8));"

arguments "--disasm"

expect_success "<function main>
[00000] Function          0
[00002] Global            1
[00004] GetLocal          1
[00006] Int               8
[00009] Call              1
[00011] Call              1
[00013] Pop
[00014] Null
[00015] Return
9 instruction(s)

<function factorial>
[00000] GetLocal          1
[00002] Int               0
[00005] Equal
[00006] JumpIfFalse       17
[00009] Pop
[00010] Int               1
[00013] Return
[00014] Jump              18
[00017] Pop
[00018] GetLocal          1
[00020] GetLocal          0
[00022] GetLocal          1
[00024] Int               1
[00027] Subtract
[00028] Call              1
[00030] Multiply
[00031] Return
[00032] Null
[00033] Return
19 instruction(s)"

run
