#!/bin/sh

. test/__test

title "Option: --dump"

script "fn factorial(n) {
  if (n == 0)
    return 1;
  return n * factorial(n - 1);
}

println(factorial(8));"

arguments "--dump"

expect_status_success

run
