#!/bin/sh

. test/test

title "Print scalar values"

script "println(null);
println(false);
println(true);
println(123);
println(4.56);
println('foo');"

expect_success "null
false
true
123
4.56
foo"

run
