#!/bin/sh

. test/__test

title "Set array element"

script "var arr1 = ['foo'];
arr1[0] = 'bar';
println(arr1);

var arr2 = [['foo']];
arr2[0][0] = 'bar';
println(arr2);

var arr3 = [[['foo']]];
arr3[0][0][0] = 'bar';
println(arr3);

var arr4 = [['foo', 'bar', 'baz']];
arr4[0][1] = 'qux';
println(arr4);"

expect_success "['bar']
[['bar']]
[[['bar']]]
[['foo', 'qux', 'baz']]"

run
