#!/bin/sh

. test/__test

title "Strcut: initializer"

script "println({});
println({a: 1});
println({a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10});

struct Foo {
  a,
  b
}
println(Foo{1, 2});"

expect_success "{}
{a: 1}
{a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10}
{a: 1, b: 2}"

run
