#!/bin/sh

. test/__test

title "Strcut: declaration and initialization"

script "struct Foo {
  a, b
}
println(Foo{1, 2});

let Bar = struct {
  c, d
};
println(Bar{3, 4});"

expect_success "{a: 1, b: 2}
{c: 3, d: 4}"

run
