#!/bin/sh

. test/__test

title "Strcut instantiator"

script "println({});
println({a: 1});
println({a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10});"

expect_success "{}
{a: 1}
{a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10}"

run
