#!/bin/sh

. test/__test

title "Variable declaration"

script "let a = 1;
let [b, c] = [2, 3];
let mut d;
let mut e = 4;
let [f, g] = ['foo', 'bar'];
let [mut h] = ['baz'];
let [i, mut j] = ['qux', 'quux'];

println(a);
println(b);
println(c);
println(d);
println(e);
println(f);
println(g);
println(h);
println(i);
println(j);"

expect_success "1
2
3
null
4
foo
bar
baz
qux
quux"

run
