#!/bin/sh

. test/__test

title "Variable declaration"

script "let a = 1;
let [b, c] = [2, 3];
var d;
var e = 4;
var [f, g] = ['foo', 'bar'];

println(a);
println(b);
println(c);
println(d);
println(e);
println(f);
println(g);"

expect_success "1
2
3
null
4
foo
bar"

run
