#!/bin/sh

. tests/tests

title "Append array element"

script "let arr1 = [];
arr1[] = 'foo';
echo arr1;

let arr2 = [[]];
arr2[0][] = 'foo';
echo arr2;

let arr3 = [[[]]];
arr3[0][0][] = 'foo';
echo arr3;"

expect_success "['foo']
[['foo']]
[[['foo']]]"

run
