#!/bin/sh

. tests/tests

title "Array difference"

script "echo [] - ['foo'];
echo ['foo'] - [];
echo ['foo', 'bar', 'baz'] - ['bar'];
var arr = ['foo', 'bar', 'baz', 'bar', 'qux'];
echo arr - ['bar', 'baz'];"

expect_success "[]
['foo']
['foo', 'baz']
['foo', 'qux']"

run
