#!/bin/sh

. tests/tests

title "Delete array element"

script "var arr = [1, 2, 3, ['foo', 'bar', 'baz']];
delete arr[1];
echo arr;

delete arr[2][1];
echo arr;"

expect_success "[1, 3, ['foo', 'bar', 'baz']]
[1, 3, ['foo', 'baz']]"

run
