#!/bin/sh

. tests/tests

title "Error invalid range: capacity must be between 0 and 2147483647"

script "let arr = array(-1);"

expect_failure "fatal error: invalid range: capacity must be between 0 and 2147483647"

run
