name: Build for release with extensions

on:
  release:
    types:
      - created

jobs:

  ubuntu-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies (APT packages)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev
        sudo apt-get install -y libmysqlclient-dev
        sudo apt-get install -y libgmp3-dev
    - name: Installing dependency hiredis
      run: |
        git clone https://github.com/redis/hiredis.git
        cd hiredis
        git fetch --all --tags
        git checkout tags/v1.0.2
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build
    - name: Installing dependency fcgi2
      run: |
        git clone https://github.com/FastCGI-Archives/fcgi2.git
        cd fcgi2
        libtoolize && aclocal && automake --add-missing && autoconf
        ./autogen.sh
        ./configure
        make
        sudo make install
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXTENSIONS=On
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake

  macos-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies (Homebrew packages)
      run: |
        brew reinstall fcgi
        brew install mysql-client
        brew reinstall gmp
    - name: Installing dependency hiredis
      run: |
        git clone https://github.com/redis/hiredis.git
        cd hiredis
        git fetch --all --tags
        git checkout tags/v1.0.2
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXTENSIONS=On
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake

  windows-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing tool vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout 96c35a683eed6695172ebe30d752654d9c0658e6
        bootstrap-vcpkg.bat
        vcpkg integrate install
    - name: Installing dependencies (vcpkg packages)
      run: |
        vcpkg install curl:x64-windows
        vcpkg install fastcgi:x64-windows
        vcpkg install libmysql:x64-windows
        vcpkg install gmp:x64-windows
    - name: Installing dependency hiredis
      run: |
        git clone https://github.com/redis/hiredis.git
        cd hiredis
        git fetch --all --tags
        git checkout tags/v1.0.2
        cmake -B build
        cmake --build build --config Release
        cmake --install build
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -S . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_EXTENSIONS=On
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config Release
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake
