name: Build and test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake and build
      run: ${{ github.workspace }}/scripts/build.sh
    - name: Running tests
      run: |
        ${{ github.workspace }}/scripts/test.sh
      env:
        HOOK_HOME: ${{ github.workspace }}
    - name: Code coverage
      run: |
        gcov src/*.c
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake and build
      run: ${{ github.workspace }}/scripts/build.sh
    - name: Running tests
      run: |
        ${{ github.workspace }}/scripts/test.sh
      env:
        HOOK_HOME: ${{ github.workspace }}

  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure CMake and build
      run: ${{ github.workspace }}/scripts/build.bat
    - name: Running tests
      run: |
        ${{ github.workspace }}/scripts/test.bat
      env:
        HOOK_HOME: ${{ github.workspace }}
