name: macOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake and build
      run: ${{ github.workspace }}/scripts/build.sh
    - name: Running tests
      run: |
        ${{ github.workspace }}/scripts/test.sh
      env:
        HOOK_HOME: ${{ github.workspace }}
