name: Ubuntu build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake and build
      run: ${{ github.workspace }}/scripts/build.sh
    - name: Running tests
      run: |
        ${{ github.workspace }}/scripts/test.sh
      env:
        HOOK_HOME: ${{ github.workspace }}
    - name: Code coverage
      run: |
        gcov src/*.c
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
