name: Ubuntu release

on:
  release:
    types:
      - created

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake and build for release
      run: ${{ github.workspace }}/scripts/pack.sh
    - name: Upload asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/package/*.tar.gz
        overwrite: true
